# Copyright (C) 2019-2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/james/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/james

PRODUCT_COPY_FILES += \
    vendor/motorola/james/proprietary/lib/libdualcameraddm.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdualcameraddm.so \
    vendor/motorola/james/proprietary/lib/libjni_dualcamera.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libjni_dualcamera.so \
    vendor/motorola/james/proprietary/lib/libqvrcamera_client.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqvrcamera_client.so \
    vendor/motorola/james/proprietary/vendor/bin/hw/android.hardware.biometrics.fingerprint@2.1-service-ets:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.biometrics.fingerprint@2.1-service-ets \
    vendor/motorola/james/proprietary/vendor/bin/hw/android.hardware.gatekeeper@1.0-service-qti:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.gatekeeper@1.0-service-qti \
    vendor/motorola/james/proprietary/vendor/bin/hw/android.hardware.keymaster@3.0-service-qti:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.keymaster@3.0-service-qti \
    vendor/motorola/james/proprietary/vendor/bin/sensors.qti:$(TARGET_COPY_OUT_VENDOR)/bin/sensors.qti \
    vendor/motorola/james/proprietary/vendor/etc/acdbdata/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/motorola/james/proprietary/vendor/etc/acdbdata/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/General_cal.acdb \
    vendor/motorola/james/proprietary/vendor/etc/acdbdata/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Global_cal.acdb \
    vendor/motorola/james/proprietary/vendor/etc/acdbdata/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Handset_cal.acdb \
    vendor/motorola/james/proprietary/vendor/etc/acdbdata/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Hdmi_cal.acdb \
    vendor/motorola/james/proprietary/vendor/etc/acdbdata/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Headset_cal.acdb \
    vendor/motorola/james/proprietary/vendor/etc/acdbdata/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Speaker_cal.acdb \
    vendor/motorola/james/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service-ets.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service-ets.rc \
    vendor/motorola/james/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/motorola/james/proprietary/vendor/etc/init/android.hardware.keymaster@3.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@3.0-service-qti.rc \
    vendor/motorola/james/proprietary/vendor/etc/init/init.ets.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.ets.rc \
    vendor/motorola/james/proprietary/vendor/lib/libS5k2l7Pdaf.so:$(TARGET_COPY_OUT_VENDOR)/lib/libS5k2l7Pdaf.so \
    vendor/motorola/james/proprietary/vendor/lib/libS5k2l7PdafCamif.so:$(TARGET_COPY_OUT_VENDOR)/lib/libS5k2l7PdafCamif.so \
    vendor/motorola/james/proprietary/vendor/lib/libSonyDefocus.so:$(TARGET_COPY_OUT_VENDOR)/lib/libSonyDefocus.so \
    vendor/motorola/james/proprietary/vendor/lib/libSonyDualPDLibrary.so:$(TARGET_COPY_OUT_VENDOR)/lib/libSonyDualPDLibrary.so \
    vendor/motorola/james/proprietary/vendor/lib/libSonyDualPDParam.so:$(TARGET_COPY_OUT_VENDOR)/lib/libSonyDualPDParam.so \
    vendor/motorola/james/proprietary/vendor/lib/libactuator_dw9714p.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9714p.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromaflash.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromaflash.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_byd_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_byd_common.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_byd_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_byd_cpp_hfr_120.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_byd_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_byd_cpp_liveshot.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_byd_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_byd_cpp_preview.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_byd_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_byd_cpp_snapshot.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_byd_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_byd_cpp_video.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_byd_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_byd_default_video.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_byd_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_byd_hfr_120.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_byd_hfr_120_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_byd_hfr_120_3a.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_byd_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_byd_postproc.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_byd_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_byd_preview.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_byd_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_byd_snapshot.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_byd_zsl_preview_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_byd_zsl_preview_3a.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_byd_zsl_video_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_byd_zsl_video_3a.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_common.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_cpp_hfr_120.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_cpp_liveshot.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_cpp_preview.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_cpp_snapshot.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_cpp_video.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_default_video.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_hfr_120.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_hfr_120_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_hfr_120_3a.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_postproc.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_preview.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_snapshot.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_zsl_preview_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_zsl_preview_3a.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi556_zsl_video_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi556_zsl_video_3a.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_byd_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_byd_common.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_byd_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_byd_cpp_hfr_120.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_byd_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_byd_cpp_liveshot.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_byd_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_byd_cpp_preview.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_byd_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_byd_cpp_snapshot.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_byd_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_byd_cpp_video.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_byd_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_byd_default_video.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_byd_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_byd_hfr_120.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_byd_hfr_120_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_byd_hfr_120_3a.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_byd_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_byd_postproc.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_byd_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_byd_preview.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_byd_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_byd_snapshot.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_byd_zsl_preview_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_byd_zsl_preview_3a.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_byd_zsl_video_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_byd_zsl_video_3a.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_common.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_cpp_hfr_120.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_cpp_liveshot.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_cpp_preview.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_cpp_snapshot.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_cpp_video.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_default_video.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_hfr_120.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_hfr_120_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_hfr_120_3a.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_postproc.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_preview.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_snapshot.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_zsl_preview_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_zsl_preview_3a.so \
    vendor/motorola/james/proprietary/vendor/lib/libchromatix_mot_hi846_zsl_video_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_mot_hi846_zsl_video_3a.so \
    vendor/motorola/james/proprietary/vendor/lib/libgralloc1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgralloc1.so \
    vendor/motorola/james/proprietary/vendor/lib/libjpegdhw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegdhw.so \
    vendor/motorola/james/proprietary/vendor/lib/libjpegdmahw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegdmahw.so \
    vendor/motorola/james/proprietary/vendor/lib/libjpegehw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegehw.so \
    vendor/motorola/james/proprietary/vendor/lib/libmmcamera_mot_hi556.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_mot_hi556.so \
    vendor/motorola/james/proprietary/vendor/lib/libmmcamera_mot_hi556_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_mot_hi556_eeprom.so \
    vendor/motorola/james/proprietary/vendor/lib/libmmcamera_mot_hi846.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_mot_hi846.so \
    vendor/motorola/james/proprietary/vendor/lib/libmmcamera_mot_hi846_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_mot_hi846_eeprom.so \
    vendor/motorola/james/proprietary/vendor/lib/libmot_lux_standardization.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmot_lux_standardization.so \
    vendor/motorola/james/proprietary/vendor/lib/liboptizoom.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboptizoom.so \
    vendor/motorola/james/proprietary/vendor/lib/libqomx_core.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_core.so \
    vendor/motorola/james/proprietary/vendor/lib/libqomx_jpegdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegdec.so \
    vendor/motorola/james/proprietary/vendor/lib/libqomx_jpegenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegenc.so \
    vendor/motorola/james/proprietary/vendor/lib/libqomx_jpegenc_pipe.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegenc_pipe.so \
    vendor/motorola/james/proprietary/vendor/lib/libremosaic_daemon.so:$(TARGET_COPY_OUT_VENDOR)/lib/libremosaic_daemon.so \
    vendor/motorola/james/proprietary/vendor/lib/libseemore.so:$(TARGET_COPY_OUT_VENDOR)/lib/libseemore.so \
    vendor/motorola/james/proprietary/vendor/lib/libsensor1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsensor1.so \
    vendor/motorola/james/proprietary/vendor/lib/libsensor_reg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsensor_reg.so \
    vendor/motorola/james/proprietary/vendor/lib/libtrueportrait.so:$(TARGET_COPY_OUT_VENDOR)/lib/libtrueportrait.so \
    vendor/motorola/james/proprietary/vendor/lib/libubifocus.so:$(TARGET_COPY_OUT_VENDOR)/lib/libubifocus.so \
    vendor/motorola/james/proprietary/vendor/lib/rfsa/adsp/tas2560_TI.bin:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/tas2560_TI.bin \
    vendor/motorola/james/proprietary/vendor/lib/sensor_calibrate.so:$(TARGET_COPY_OUT_VENDOR)/lib/sensor_calibrate.so \
    vendor/motorola/james/proprietary/vendor/lib/sensors.hal.tof.so:$(TARGET_COPY_OUT_VENDOR)/lib/sensors.hal.tof.so \
    vendor/motorola/james/proprietary/vendor/lib/sensors.rp.so:$(TARGET_COPY_OUT_VENDOR)/lib/sensors.rp.so \
    vendor/motorola/james/proprietary/vendor/lib/sensors.ssc.so:$(TARGET_COPY_OUT_VENDOR)/lib/sensors.ssc.so \
    vendor/motorola/james/proprietary/vendor/lib/vendor.qti.hardware.sensorscalibrate@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.qti.hardware.sensorscalibrate@1.0.so \
    vendor/motorola/james/proprietary/vendor/lib64/hw/android.hardware.gatekeeper@1.0-impl-qti.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/android.hardware.gatekeeper@1.0-impl-qti.so \
    vendor/motorola/james/proprietary/vendor/lib64/hw/android.hardware.keymaster@3.0-impl-qti.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/android.hardware.keymaster@3.0-impl-qti.so \
    vendor/motorola/james/proprietary/vendor/lib64/libets_fp_et5.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libets_fp_et5.so \
    vendor/motorola/james/proprietary/vendor/lib64/libets_teeclient.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libets_teeclient.so \
    vendor/motorola/james/proprietary/vendor/lib64/libkeymasterdeviceutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeymasterdeviceutils.so \
    vendor/motorola/james/proprietary/vendor/lib64/libkeymasterprovision.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeymasterprovision.so \
    vendor/motorola/james/proprietary/vendor/lib64/libkeymasterutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libkeymasterutils.so \
    vendor/motorola/james/proprietary/vendor/lib64/libsensor1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsensor1.so \
    vendor/motorola/james/proprietary/vendor/lib64/libsensor_reg.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsensor_reg.so \
    vendor/motorola/james/proprietary/vendor/lib64/sensor_calibrate.so:$(TARGET_COPY_OUT_VENDOR)/lib64/sensor_calibrate.so \
    vendor/motorola/james/proprietary/vendor/lib64/sensors.rp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/sensors.rp.so \
    vendor/motorola/james/proprietary/vendor/lib64/sensors.ssc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/sensors.ssc.so \
    vendor/motorola/james/proprietary/vendor/lib64/vendor.egistec.hardware.fingerprint@2.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.egistec.hardware.fingerprint@2.0.so \
    vendor/motorola/james/proprietary/vendor/lib64/vendor.qti.hardware.sensorscalibrate@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.sensorscalibrate@1.0.so

PRODUCT_PACKAGES += \
    libts_detected_face_hal \
    libts_face_beautify_hal
